In [2]:
f= open ("D://pari.txt","w")
f.write("sid is a good boy.")
f.close()

In [3]:
f= open("D://pari.txt","r")
print(f.read())
f= open("D://pari.txt","w")
f.write("sid is a verryyy good boy.")
f.close()
f= open("D://pari.txt","r")
print(f.read())

sid is a good boy.
sid is a verryyy good boy.


In [6]:
f= open("D://pari.txt","r")
print(f.read())
f= open("D://pari.txt","a")
f.write("\n sid is a verryyy verryyyyy verrrryyyyyyyyyy good boy.")
f.close()
f= open("D://pari.txt","r")
print(f.read())

sid is a verryyy good boy.sid is a verryyy verryyyyy good boy./n sid is a verryyy verryyyyy verrrryyyyyyyyyy good boy.
sid is a verryyy good boy.sid is a verryyy verryyyyy good boy./n sid is a verryyy verryyyyy verrrryyyyyyyyyy good boy.
 sid is a verryyy verryyyyy verrrryyyyyyyyyy good boy.


In [7]:
f= open ("D://parik.txt","w")
f.write("pari majak chal raha hai kya")
f.close()

In [8]:
import os
os.remove("D://parik.txt")

In [10]:
f= open ("D://sid1.txt","w")
f.write("sid is a good boy.")
f.close()

In [11]:
f= open("D://sid1.txt","r")
print(f.read())

sid is a good boy.


In [15]:
#overrite
f= open ("D://sid1.txt","w")
f.write("sid is a bad boy.")
#print(f.read())
f.close()

In [24]:
f= open("D://sid1.txt","r")
print(f.read())

sid is a bad boy.
 sid is a bad-good-bad boy.
 sid is a bad-good-bad boy.
 sid is a bad-good-bad boy.


In [23]:
#append
f= open ("D://sid1.txt","a")
f.write("\n sid is a bad-good-bad boy.")
f.close()

In [28]:
f= open ("D://sid1.txt","w")
l=[100,80,70,50,60]
f.close()

In [29]:
f= open("D://sid1.txt","r")
print(f.read())

#lambda function= function without name

In [5]:
 def square(a):
        return a*a
r=square(5)
 print(r)
        

25


In [7]:
#lambda
f=lambda a: a*a
r=f(5)
print(r)

25


In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [31]:
import numpy as np
print(np.__version__)

1.18.1


In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [35]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [37]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [39]:
print(arr[2] + arr[3])

7


In [40]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [42]:
print(arr[4:])

[5 6 7]


In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [44]:
print(arr[-3:-1])

[5 6]


In [45]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [46]:
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [47]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [2]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}
myvar = pd.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [3]:
#Pandas Series
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64


In [4]:
print(myvar[0])

1


In [5]:
#series(1-d)
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)


x    1
y    7
z    2
dtype: int64


In [9]:
#DataFrames(multidimension)
import pandas as pd
data = {
  "c": [420, 380, 390],
  "d": [50, 40, 45]
}

myvar = pd.DataFrame(data)
print(myvar)



     c   d
0  420  50
1  380  40
2  390  45


In [10]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [11]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [14]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 


      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [15]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


In [21]:
import pandas as pd
d={'name':['avi','pari','alisha','khesha'],'marks':[96,100,34,100]}
pd.DataFrame(d)

name  marks
0     avi     96
1    pari    100
2  alisha     34
3  khesha    100

In [26]:
marks.max()

name     pari
marks     100
dtype: object

In [29]:
marks.min()

marks    34
dtype: int64

In [33]:
 
from tkinter import *
import os
 
# Designing window for registration
 
def register():
    global register_screen
    register_screen = Toplevel(main_screen)
    register_screen.title("Register")
    register_screen.geometry("300x250")
 
    global username
    global password
    global username_entry
    global password_entry
    username = StringVar()
    password = StringVar()
 
    Label(register_screen, text="Please enter details below", bg="blue").pack()
    Label(register_screen, text="").pack()
    username_lable = Label(register_screen, text="Username * ")
    username_lable.pack()
    username_entry = Entry(register_screen, textvariable=username)
    username_entry.pack()
    password_lable = Label(register_screen, text="Password * ")
    password_lable.pack()
    password_entry = Entry(register_screen, textvariable=password, show='*')
    password_entry.pack()
    Label(register_screen, text="").pack()
    Button(register_screen, text="Register", width=10, height=1, bg="blue", command = register_user).pack()
 
 
# Designing window for login 
 
def login():
    global login_screen
    login_screen = Toplevel(main_screen)
    login_screen.title("Login")
    login_screen.geometry("300x250")
    Label(login_screen, text="Please enter details below to login").pack()
    Label(login_screen, text="").pack()
 
    global username_verify
    global password_verify
 
    username_verify = StringVar()
    password_verify = StringVar()
 
    global username_login_entry
    global password_login_entry
 
    Label(login_screen, text="Username * ").pack()
    username_login_entry = Entry(login_screen, textvariable=username_verify)
    username_login_entry.pack()
    Label(login_screen, text="").pack()
    Label(login_screen, text="Password * ").pack()
    password_login_entry = Entry(login_screen, textvariable=password_verify, show= '*')
    password_login_entry.pack()
    Label(login_screen, text="").pack()
    Button(login_screen, text="Login", width=10, height=1, command = login_verify).pack()
 
# Implementing event on register button
 
def register_user():
 
    username_info = username.get()
    password_info = password.get()
 
    file = open(username_info, "w")
    file.write(username_info + "\n")
    file.write(password_info)
    file.close()
 
    username_entry.delete(0, END)
    password_entry.delete(0, END)
 
    Label(register_screen, text="Registration Success", fg="green", font=("calibri", 11)).pack()
 
# Implementing event on login button 
 
def login_verify():
    username1 = username_verify.get()
    password1 = password_verify.get()
    username_login_entry.delete(0, END)
    password_login_entry.delete(0, END)
 
    list_of_files = os.listdir()
    if username1 in list_of_files:
        file1 = open(username1, "r")
        verify = file1.read().splitlines()
        if password1 in verify:
            login_sucess()
 
        else:
            password_not_recognised()
 
    else:
        user_not_found()
 
# Designing popup for login success
 
def login_sucess():
    global login_success_screen
    login_success_screen = Toplevel(login_screen)
    login_success_screen.title("Success")
    login_success_screen.geometry("150x100")
    Label(login_success_screen, text="Login Success").pack()
    Button(login_success_screen, text="OK", command=delete_login_success).pack()
 
# Designing popup for login invalid password
 
def password_not_recognised():
    global password_not_recog_screen
    password_not_recog_screen = Toplevel(login_screen)
    password_not_recog_screen.title("Success")
    password_not_recog_screen.geometry("150x100")
    Label(password_not_recog_screen, text="Invalid Password ").pack()
    Button(password_not_recog_screen, text="OK", command=delete_password_not_recognised).pack()
 
# Designing popup for user not found
 
def user_not_found():
    global user_not_found_screen
    user_not_found_screen = Toplevel(login_screen)
    user_not_found_screen.title("Success")
    user_not_found_screen.geometry("150x100")
    Label(user_not_found_screen, text="User Not Found").pack()
    Button(user_not_found_screen, text="OK", command=delete_user_not_found_screen).pack()
 
# Deleting popups
 
def delete_login_success():
    login_success_screen.destroy()
 
 
def delete_password_not_recognised():
    password_not_recog_screen.destroy()
 
 
def delete_user_not_found_screen():
    user_not_found_screen.destroy()
 
 
# Designing Main(first) window
 
def main_account_screen():
    global main_screen
    main_screen = Tk()
    main_screen.geometry("300x250")
    main_screen.title("Account Login")
    Label(text="Select Your Choice", bg="blue", width="300", height="2", font=("Calibri", 13)).pack()
    Label(text="").pack()
    Button(text="Login", height="2", width="30", command = login).pack()
    Label(text="").pack()
    Button(text="Register", height="2", width="30", command=register).pack()
 
    main_screen.mainloop()
 
 
main_account_screen()

In [ ]:
from tkinter import *

MyRootDialog=Tk()
#Set Tkinter Size And Location
MyRootDialog.geometry("400x250+100+100")


# Define Function for get Value
def Get_MyInputValue():
     getresult = MyEntryBox.get()   
     getresult1 = MyEntryBox1.get()
     rows=[]
     T=[["user","pass"],[getresult,getresult1]]     
     for i in range(2):
        cols = []
        for j in range(2):
            e = Entry(relief=GROOVE)
            e.grid(row=i, column=j, sticky=NSEW)
            e.insert(END, '%s' % (T[i][j]))
            cols.append(e)
        rows.append(cols)

# Create Tkinter Entry Widget
MyEntryBox = Entry(MyRootDialog, width=10)
MyEntryBox.place(x=80, y=90)
MyEntryBox1 = Entry(MyRootDialog, width=10)
MyEntryBox1.place(x=100, y=110)
email = Label(MyRootDialog, text = "Email").place(x = 30, y = 90)    
password = Label(MyRootDialog, text = "Password").place(x = 30, y = 110)
#command will call the defined function
MyTkButton = Button(MyRootDialog, height=1, width=10, text="Get text", command= Get_MyInputValue)
MyTkButton.place(x=30, y=230)

mainloop()

#######################################login#######################################

import pandas as pd
  
#making data frame from csv file
data=pd.read_csv("employee.csv")
  
#sorting data on condition
data.sort_values(["salary"], axis=0,
                 ascending=False, inplace=True)
#display salary>40000
df=data[(data['salary']>40000)]
print(df[['id','name']])
#dropna drops the rows with null values
#notna returns boolean with ans of the null
#plot scatter 
#display
data

In [1]:
import tkinter
from tkinter import *
MyRootDialog=Tk()
#Set Tkinter Size And Location
MyRootDialog.geometry("400x250+100+100")


# Define Function for get Value
def Get_MyInputValue():
     getresult = MyEntryBox.get()   
     getresult1 = MyEntryBox1.get()
     rows=[]
     T=[["user","pass"],[getresult,getresult1]]     
     for i in range(2):
        cols = []
        for j in range(2):
            e = Entry(relief=GROOVE)
            e.grid(row=i, column=j, sticky=NSEW)
            e.insert(END, '%s' % (T[i][j]))
            cols.append(e)
        rows.append(cols)

# Create Tkinter Entry Widget
MyEntryBox = Entry(MyRootDialog, width=10)
MyEntryBox.place(x=80, y=90)
MyEntryBox1 = Entry(MyRootDialog, width=10)
MyEntryBox1.place(x=100, y=110)
email = Label(MyRootDialog, text = "Email").place(x = 30, y = 90)    
password = Label(MyRootDialog, text = "Password").place(x = 30, y = 110)
#command will call the defined function
MyTkButton = Button(MyRootDialog, height=1, width=10, text="Get text", command= Get_MyInputValue)
MyTkButton.place(x=30, y=230)

mainloop()